name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-cpython38-linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        export PYBUILD_RELEASE_TAG=$(date --utc '+%Y%m%dT%H%M')
        sudo apt-get install python3-venv
        sudo ./build-linux.py --target-triple x86_64-unknown-linux-musl --python cpython-3.8 --optimizations lto --libressl

    - uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        name: cpython-3.8.5-x86_64-unknown-linux-musl-lto
        path: dist/cpython-3.8.5-x86_64-unknown-linux-musl-lto-*.tar.zst
        if-no-files-found: error
